#env
from environs import Env
env=Env()
env.read_env()

#backend
config_backend_host=env("backend_host")
config_backend_port=env.int("backend_port")

#url
config_redis_url=env("redis_url")
config_mongo_url=env("mongo_url")
config_postgres_instance=env("postgres_instance")

#aws
config_aws_access_key_id=env("aws_access_key_id")
config_aws_secret_access_key=env("aws_secret_access_key")
config_aws_s3_bucket_region=env("aws_s3_bucket_region")
config_aws_s3_bucket_name=env("aws_s3_bucket_name")
config_aws_ses_region=env("aws_ses_region")
config_aws_ses_sender=env("aws_ses_sender")

#elasticsearch
config_elasticsearch_cloud_id=env("elasticsearch_cloud_id")
config_elasticsearch_username=env("elasticsearch_username")
config_elasticsearch_password=env("elasticsearch_password")

#misc
config_jwt_secret_key=env("jwt_secret_key")
config_jwt_expire_day=env.int("jwt_expire_day")
config_token_root=env("token_root")
config_x=env.list("x")

#hardcoded
config_table=["atom","users","post","likes","comment","bookmark","report","rating","block","message","helpdesk","s3","otp","workseeker"]
config_column={
"created_at":["timestamptz",config_table],
"created_by_id":["bigint",config_table],
"updated_at":["timestamptz",["atom","users","post","comment","report","message","helpdesk","workseeker"]],
"updated_by_id":["bigint",["atom","users","post","comment","report","message","helpdesk","workseeker"]],
"is_active":["int",["atom","users","post","comment","workseeker"]],
"is_verified":["int",["atom","users","post","comment","workseeker"]],
"parent_table":["text",["likes","comment","bookmark","report","rating","block"]],
"parent_id":["bigint",["likes","comment","bookmark","report","rating","block"]],
"received_by_id":["bigint",["message"]],
"username":["text",["users"]],
"password":["text",["users"]],
"firebase_id":["text",["users"]],
"last_active_at":["timestamptz",["users"]],
"profile_pic_url":["text",["users"]],
"name":["text",["users","workseeker"]],
"gender":["text",["users","workseeker"]],
"date_of_birth":["date",["users"]],
"type":["text",["atom","users","post","helpdesk","workseeker"]],
"title":["text",["atom","users","post"]],
"description":["text",["atom","users","post","comment","report","rating","block","message","helpdesk","workseeker"]],
"file_url":["text",["atom","post","s3","workseeker"]],
"link_url":["text",["atom","post"]],
"tag":["text[]",["atom","users","post","workseeker"]],
"number":["numeric",["post"]],
"date":["date",["post"]],
"status":["text",["post","report","message","helpdesk"]],
"remark":["text",["post","report","helpdesk"]],
"email":["text",["users","post","otp","helpdesk","workseeker"]],
"mobile":["text",["users","post","otp","helpdesk","workseeker"]],
"whatsapp":["text",["users","post","workseeker"]],
"phone":["text",["users","post"]],
"country":["text",["users","post"]],
"state":["text",["users","post"]],
"city":["text",["users","post"]],
"rating":["int",["rating","helpdesk"]],
"otp":["int",["otp"]],
"metadata":["jsonb",["post"]],
"work_profile":["text",["workseeker"]],
"experience":["int",["workseeker"]],
"sector":["text",["workseeker"]],
"college":["text",["workseeker"]],
"linkedin_url":["text",["workseeker"]],
"portfolio_url":["text",["workseeker"]],
"location_current":["text",["workseeker"]],
"location_expected":["text",["workseeker"]],
"salary_type":["text",["workseeker"]],
"salary_current":["int",["workseeker"]],
"salary_expected":["int",["workseeker"]],
"past_company_count":["int",["workseeker"]],
"is_working":["int",["workseeker"]],
"joining_days":["int",["workseeker"]],
"is_pinned":["int",["post"]],
}
