#env
from environs import Env
env=Env()
env.read_env()
postgres_database_url=env("postgres_database_url")
redis_server_url=env("redis_server_url")
mongo_server_url=env("mongo_server_url")
sentry_dsn=env("sentry_dsn")
jwt_secret_key=env("jwt_secret_key")
root_secret_key=env("root_secret_key")
elasticsearch_username=env("elasticsearch_username")
elasticsearch_password=env("elasticsearch_password")
elasticsearch_cloud_id=env("elasticsearch_cloud_id")
sns_region_name=env("sns_region_name")
sns_access_key_id=env("sns_access_key_id")
sns_secret_access_key=env("sns_secret_access_key")
ses_region_name=env("ses_region_name")
ses_access_key_id=env("ses_access_key_id")
ses_secret_access_key=env("ses_secret_access_key")
s3_access_key_id=env("s3_access_key_id")
s3_secret_access_key=env("s3_secret_access_key")
rekognition_region_name=env("rekognition_region_name")
rekognition_access_key_id=env("rekognition_access_key_id")
rekognition_secret_access_key=env("rekognition_secret_access_key")
openai_secret_key=env("openai_secret_key")

#postgres
postgres_prequery=["create extension if not exists postgis"]
postgres_table=["users","post","box","atom","likes","bookmark","report","block","rating","comment","message","helpdesk","otp","log"]
postgres_column={
"id":["bigint",postgres_table],
"created_at":["timestamptz",postgres_table],
"created_by_id":["bigint",postgres_table],
"is_deleted":["int",["users","post","box","atom"]],
"updated_at":["timestamptz",["users","post","box","atom","report","comment","message","helpdesk"]],
"updated_by_id":["bigint",["users","post","box","atom","report","comment","message","helpdesk"]],
"is_active":["int",["users","post"]],
"is_verified":["int",["users","post"]],
"is_protected":["int",["users","post","box","atom"]],
"parent_table":["text",["likes","bookmark","report","block","rating","comment","message"]],
"parent_id":["bigint",["likes","bookmark","report","block","rating","comment","message"]],
"type":["text",["users","post","box","atom","helpdesk"]],
"status":["text",["report","helpdesk","message"]],
"remark":["text",["report","helpdesk"]],
"rating":["numeric",["rating","atom","post"]],
"metadata":["jsonb",["users","post","box","atom"]],
"username":["text",["users"]],
"password":["text",["users"]],
"google_id":["text",["users"]],
"profile_pic_url":["text",["users"]],
"last_active_at":["timestamptz",["users"]],
"name":["text",["users"]],
"email":["text",["users","post","box","atom","otp","helpdesk"]],
"mobile":["text",["users","post","box","atom","otp","helpdesk"]],
"date_of_birth":["date",["users"]],
"title":["text",["users","post","box","atom"]],
"description":["text",["users","post","box","atom","report","block","comment","message","helpdesk"]],
"file_url":["text",["post","box","atom","comment","message"]],
"link_url":["text",["post","box","atom"]],
"tag":["text",["users","post","box","atom"]],
"otp":["int",["otp"]],
"tag_array":["text[]",["atom"]],
"location":["geography(POINT)",["users","post","box","atom"]],
"request_url_path":["text",["log"]],
"request_query_param":["jsonb",["log"]],
"request_body":["jsonb",["log"]],
"interest":["text",["users"]],
"skill":["text",["users"]],
"gender":["text",["users"]],
"country":["text",["users"]],
"state":["text",["users"]],
"city":["text",["users"]],
"response_time_ms":["numeric",["log"]],
"api_access":["text",["users"]],
}
postgres_notnull={"id":postgres_table,"created_at":postgres_table,"parent_table":["likes","bookmark","report","block","rating","comment","message"],"parent_id":["likes","bookmark","report","block","rating","comment","message"]}
postgres_default=[["created_at","now()",postgres_table]]
postgres_unique={"username":["users"],"created_by_id,parent_table,parent_id":["likes","bookmark","report","block"]}
postgres_index={
"id":["btree",postgres_table],
"created_at":["brin",postgres_table],
"created_by_id":["btree",postgres_table],
"is_deleted":["btree",["users","post","box","atom"]],
"is_active":["btree",["users","post"]],
"is_verified":["btree",["users","post"]],
"parent_table":["btree",["likes","bookmark","report","block","rating","comment","message"]],
"parent_id":["btree",["likes","bookmark","report","block","rating","comment","message"]],
"type":["btree",["users","post","box","atom","helpdesk"]],
"status":["btree",["report","helpdesk","message"]],
"email":["btree",["users","post","box","atom","otp","helpdesk"]],
"password":["btree",["users"]],
"location":["gist",["users","post","box","atom"]],
"tag":["btree",["users","post","box","atom"]],
"tag_array":["gin",["atom"]],
}
postgres_postquery=[
"insert into users (username,password) values ('atom','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3') on conflict do nothing;",
"create or replace rule rule_delete_disable_root_user as on delete to users where old.id=1 do instead nothing;",
"CREATE OR REPLACE FUNCTION function_set_updated_at_now() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ language 'plpgsql';",
"CREATE OR REPLACE FUNCTION function_delete_disable_bulk() RETURNS trigger LANGUAGE plpgsql AS $$DECLARE n bigint := TG_ARGV[0]; BEGIN IF (SELECT count(*) FROM deleted_rows) <= n IS NOT TRUE THEN RAISE EXCEPTION 'cant delete more than % rows', n; END IF; RETURN OLD; END;$$;",
"CREATE OR REPLACE TRIGGER trigger_delete_disable_bulk_users AFTER DELETE ON users REFERENCING OLD TABLE AS deleted_rows FOR EACH STATEMENT EXECUTE PROCEDURE function_delete_disable_bulk(1);",
]
