config_table=["atom","users","post","likes","comment","bookmark","report","rating","block","message","helpdesk","s3","otp","workseeker"]

#column:table,datatype,default,checkin,index
config_column={
"created_at":[config_table,"timestamptz","now()",None,1],
"created_by_id":[config_table,"bigint",None,None,1],
"updated_at":[["atom","users","post","comment","report","message","helpdesk","workseeker"],"timestamptz",None,None,0],
"updated_by_id":[["atom","users","post","comment","report","message","helpdesk","workseeker"],"bigint",None,None,0],
"is_active":[["atom","users","post","comment","workseeker"],"int",1,(0,1),1],
"is_verified":[["atom","users","post","comment","workseeker"],"int",0,(0,1),1],
"parent_table":[["likes","comment","bookmark","report","rating","block"],"text",None,None,1],
"parent_id":[["likes","comment","bookmark","report","rating","block"],"bigint",None,None,1],
"received_by_id":[["message"],"bigint",None,None,1],
"last_active_at":[["users"],"timestamptz","now()",None,None,0],
"firebase_id":[["users"],"text",None,None,1],
"otp":[["otp"],"int",None,None,1],
"metadata":[["post"],"jsonb",None,None,0],

"username":[["users"],"text",None,None,1],
"password":[["users"],"text",None,None,1],
"profile_pic_url":[["users"],"text",None,None,0],
"date_of_birth":[["users"],"date",None,None,0],
"name":[["users","workseeker"],"text",None,None,0],
"gender":[["users","workseeker"],"text",None,None,0],
"email":[["users","post","otp","helpdesk","workseeker"],"text",None,None,1],
"mobile":[["users","post","otp","helpdesk","workseeker"],"text",None,None,1],
"whatsapp":[["users","post","workseeker"],"text",None,None,1],
"phone":[["users","post","workseeker"],"text",None,None,1],
"country":[["users","post",],"text",None,None,1],
"state":[["users","post"],"text",None,None,1],
"city":[["users","post"],"text",None,None,1],
  
"type":[["post","atom","users","helpdesk"],"text",None,None,1],
"title":[["post","atom","users"],"text",None,None,0],
"description":[["post","atom","users","comment","report","rating","block","message","helpdesk","workseeker"],"text",None,None,0],
"file_url":[["post","atom","s3"],"text",None,None,0],
"link_url":[["post","atom"],"text",None,None,0],
"tag":[["post","atom","users","workseeker"],"text[]",None,None,1],
"number":[["post"],"numeric",None,None,0],
"date":[["post"],"date",None,None,0],
"status":[["post","report","message","helpdesk"],"text",None,None,1],
"remark":[["post","report","helpdesk"],"text",None,None,0],
"rating":[["post","rating","helpdesk"],"int",None,None,0],
"is_pinned":[["post"],"int",0,None,(0,1),1],

"work_type":[["workseeker"],"text",None,None,1],
"work_profile":[["workseeker"],"text",None,None,1],
"degree":[["workseeker"],"text",None,None,0],
"college":[["workseeker"],"text",None,None,0],
"linkedin_url":[["workseeker"],"text",None,None,0],
"portfolio_url":[["workseeker"],"text",None,None,0],
"experience":[["workseeker"],"int",None,None,1],
"experience_work_profile":[["workseeker"],"int",None,None,0],
"is_working":[["workseeker"],"int",None,(0,1),1],
"location_current":[["workseeker"],"text",None,None,1],
"location_expected":[["workseeker"],"text",None,None,1],
"currency":[["workseeker"],"text",None,None,0],
"salary_frequency":[["workseeker"],"text",None,None,0],
"salary_current":[["workseeker"],"int",None,None,0],
"salary_expected":[["workseeker"],"int",None,None,0],
"sector":[["workseeker"],"text",None,None,0],
"past_company_count":[["workseeker"],"int",None,None,0],
"past_company_name":[["workseeker"],"text",None,None,0],
"marital_status":[["workseeker"],"text",None,None,0],
"physical_disability":[["workseeker"],"text",None,None,0],
"hobby":[["workseeker"],"text",None,None,0],
"language":[["workseeker"],"text",None,None,0],
"joining_days":[["workseeker"],"int",None,None,0],
"career_break_month":[["workseeker"],"int",None,None,0],
"resume_url":[["workseeker"],"text",None,None,0],
"achievement":[["workseeker"],"text",None,None,0],
"certificate":[["workseeker"],"text",None,None,0],
"project":[["workseeker"],"text",None,None,0],
"is_founder":[["workseeker"],"int",None,(0,1),1],
}

class schema_atom(BaseModel):
    created_by_id:int|None=None
    is_active:int|None=None

   
   
  
   received_by_id:int|None=None
   
   is_verified:int|None=None
   parent_table:str|None=None
   parent_id:int|None=None
   username:str|None=None
   profile_pic_url:str|None=None
   name:str|None=None
   gender:str|None=None
   date_of_birth:datetime|None=None
   type:str|None=None
   title:str|None=None
   description:str|None=None
   file_url:str|None=None
   link_url:str|None=None
   tag:list|None=None
   number:float|None=None
   date:datetime|None=None
   status:str|None=None
   remark:str|None=None
   email:str|None=None
   mobile:str|None=None
   whatsapp:str|None=None
   phone:str|None=None
   country:str|None=None
   state:str|None=None
   city:str|None=None
   rating:int|None=None
   metadata:dict|None=None
   work_profile:str|None=None
   experience:int|None=None
   sector:str|None=None
   college:str|None=None
   linkedin_url:str|None=None
   portfolio_url:str|None=None
   location_current:str|None=None
   location_expected:str|None=None
   salary_type:str|None=None
   salary_current:int|None=None
   salary_expected:int|None=None
   past_company_count:int|None=None
   is_working:int|None=None
   joining_days:int|None=None
